providers:
  consulCatalog:
    endpoint:
      address: "http://consul:8500"
  file:
    filename: /etc/traefik/dynamic_conf.yml

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

ping:
  entryPoint: "web"

api:
  insecure: true
  dashboard: true